telegram:
  token: "7966861727:AAHE-TDH2sZNxWhwRSZO2B48-4cKP6cuCE0"  # Thay bằng token của bot Telegram của bạn
  chat_id: "5184726235"          # Thay bằng chat ID của bạn

# Trading Parameters
trading:
  max_trades: 5
  risk_percent: 1.0
  default_leverage: 5
  min_volume_usdt: 1000000
  update_interval: 300  # 5 minutes

  websocket:
  host: "localhost"
  port: 8765

